// packages/adapter-react/example/src/App.tsx
import React, { useEffect, useState } from 'react'
import { localStorageDetector } from 'typesafe-i18n/detectors'
import './App.css'
import Child from './Child'
import TypesafeI18n from './i18n/i18n-react'
import { detectLocale } from './i18n/i18n-util'
import { loadLocaleAsync } from './i18n/i18n-util.async'

const detectedLocale = detectLocale(localStorageDetector)

function App() {
	const [wasLoaded, setWasLoaded] = useState(false)

	useEffect(() => {
		loadLocaleAsync(detectedLocale).then(() => setWasLoaded(true))
	}, [])

	if (!wasLoaded) return null

	return (
		<TypesafeI18n locale={detectedLocale}>
			<div className="App">
				<Child />
			</div>
		</TypesafeI18n>
	)
}

export default App

// packages/adapter-solid/example/src/App.tsx
import { createEffect, createSignal, Show } from 'solid-js'
import { localStorageDetector } from 'typesafe-i18n/detectors'
import Child from './Child'
import TypesafeI18n from './i18n/i18n-solid'
import { detectLocale } from './i18n/i18n-util'
import { loadLocaleAsync } from './i18n/i18n-util.async'

const detectedLocale = detectLocale(localStorageDetector)

function App() {
	const [wasLoaded, setWasLoaded] = createSignal(false)

	createEffect(() => {
		loadLocaleAsync(detectedLocale).then(() => setWasLoaded(true))
	})

	return (
		<Show when={wasLoaded()}>
			<TypesafeI18n locale={detectedLocale}>
				<div className="App">
					<Child />
				</div>
			</TypesafeI18n>
		</Show>
	)
}

export default App
