// packages/adapter-react/example/src/Child.tsx
import React, { ChangeEventHandler, useContext, useState } from 'react'
import './App.css'
import { I18nContext } from './i18n/i18n-react'
import type { Locales } from './i18n/i18n-types'
import { locales } from './i18n/i18n-util'
import { loadLocaleAsync } from './i18n/i18n-util.async'
import logo from './logo.svg'

function Child() {
	const { locale, LL, setLocale } = useContext(I18nContext)

	const [name, setName] = useState('John')

	const onLocaleSelected: ChangeEventHandler<HTMLSelectElement> = async ({ target }) => {
		const locale = target.value as Locales
		localStorage.setItem('lang', locale)
		await loadLocaleAsync(locale)
		setLocale(locale)
	}

	const onNameChange: ChangeEventHandler<HTMLInputElement> = ({ target }) => setName(target.value)

	return (
		<header className="App-header">
			<label>
				{LL.SELECTED_LOCALE()}
				<select value={locale || ''} onChange={onLocaleSelected}>
					<option value="" disabled>
						{LL.CHOOSE_LOCALE()}
					</option>
					{locales.map((locale) => (
						<option key={locale} value={locale}>
							{locale}
						</option>
					))}
				</select>
			</label>

			<hr />

			{LL.HI({ name })}
			<label>
				{LL.YOUR_NAME()}
				<input type="text" value={name} onChange={onNameChange} />
			</label>

			<hr />

			{LL.TODAY({ date: new Date() })}

			<hr />

			<img src={logo} className="App-logo" alt="logo" />

			<p dangerouslySetInnerHTML={{ __html: LL.EDIT_AND_SAVE() }}></p>
			<a className="App-link" href="https://reactjs.org" target="_blank" rel="noopener noreferrer">
				{LL.LEARN_REACT()}
			</a>
		</header>
	)
}

export default Child

// packages/adapter-solid/example/src/Child.tsx
import { createSignal, JSX } from 'solid-js'
import './App.css'
import { useI18nContext } from './i18n/i18n-solid'
import type { Locales } from './i18n/i18n-types'
import { locales } from './i18n/i18n-util'
import { loadLocaleAsync } from './i18n/i18n-util.async'
import logo from './logo.svg'

function Child() {
	const { locale, LL, setLocale } = useI18nContext()

	const [name, setName] = createSignal('John')

	const onLocaleSelected: JSX.DOMAttributes<HTMLSelectElement>['onChange'] = async ({ target }) => {
		const locale = (target as HTMLInputElement).value as Locales
		localStorage.setItem('lang', locale)
		await loadLocaleAsync(locale)
		setLocale(locale)
	}

	const onNameChange: JSX.DOMAttributes<HTMLInputElement>['onInput'] = ({ target }) =>
		setName((target as HTMLInputElement).value)

	return (
		<header className="header">
			{locale}
			<label>
				{LL().SELECTED_LOCALE()}
				<select onChange={onLocaleSelected}>
					<option value="" disabled>
						{LL().CHOOSE_LOCALE()}
					</option>
					{locales.map((loc) => (
						<option value={loc} selected={locale() === loc}>
							{loc}
						</option>
					))}
				</select>
			</label>

			<hr />

			{LL().HI({ name: name() })}
			<label>
				{LL().YOUR_NAME()}
				<input type="text" value={name()} onInput={onNameChange} />
			</label>

			<hr />

			{LL().TODAY({ date: new Date() })}

			<hr />

			<img src={logo} className="logo" alt="logo" />

			<p innerHTML={LL().EDIT_AND_SAVE()} />
			<a className="link" href="https://github.com/solidjs/solid" target="_blank" rel="noopener noreferrer">
				{LL().LEARN_SOLID()}
			</a>
		</header>
	)
}

export default Child
