// examples/svelte/src/App.svelte
<script lang="ts">
	import { localStorageDetector } from 'typesafe-i18n/detectors'
	import { onMount } from 'svelte'

	import LL, { initI18n, locale, setLocale } from './i18n/i18n-svelte'
	import type { Locales } from './i18n/i18n-types'
	import { detectLocale, locales } from './i18n/i18n-util'

	export let name: string

	onMount(async () => {
		const detectedLocale = detectLocale(localStorageDetector)
		await initI18n(detectedLocale)
		console.log(LL.STARTUP())
		localeToSelect = $locale
	})

	let localeToSelect: Locales
	$: localeToSelect && setLocale(localeToSelect)

	$: $locale && localStorage.setItem('lang', $locale)

	let nrOfApples = 1
	let nrOfBananas = 2

</script>

<main>
	<label>
		{$LL.SELECTED_LOCALE()}
		<select bind:value={localeToSelect}>
			<option value="" selected disabled>{$LL.CHOOSE_LOCALE()}</option>
			{#each locales as locale}
				<option value={locale}>{locale}</option>
			{/each}
		</select>
	</label>

	<hr />

	<h1>{$LL.HI({ name })}</h1>
	<p>{@html $LL.TUTORIAL({ link: 'https://svelte.dev/tutorial' })}</p>

	<hr />

	{$LL.TODAY({ date: new Date() })}

	<label>
		{$LL.YOUR_NAME()}
		<input type="text" bind:value={name} />
	</label>

	<hr />

	<label>
		{$LL.APPLES_LABEL()}:
		<input type="number" bind:value={nrOfApples} min={0} />
	</label>

	<label>
		{$LL.BANANAS_LABEL()}:
		<input type="number" bind:value={nrOfBananas} min={0} />
	</label>

	{$LL.FRUITS({ nrOfApples, nrOfBananas })}
</main>

<style>
	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	h1 {
		color: #ff3e00;
		text-transform: uppercase;
		font-size: 4em;
		font-weight: 100;
	}

	label,
	hr {
		margin: 30px;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}

</style>

// packages/adapter-angular/example/src/app/app.component.ts
import { Component } from '@angular/core'
import { localStorageDetector } from 'typesafe-i18n/detectors'
import type { Locales, TranslationFunctions } from '../i18n/i18n-types'
import { detectLocale, locales } from '../i18n/i18n-util'
import { loadLocaleAsync } from '../i18n/i18n-util.async'
import { I18nService } from '../i18n/i18n.service'

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss'],
})
export class AppComponent {
	title = 'angular'

	selectedLocale: Locales

	locales = locales

	now = new Date()

	nrOfApples = 1
	nrOfBananas = 2

	constructor(private i18nService: I18nService) {
		this.selectedLocale = detectLocale(localStorageDetector)
		this.setLocale().then(() => {
			// eslint-disable-next-line no-console
			console.log(this.LL.STARTUP())
		})
	}

	get LL(): TranslationFunctions {
		return this.i18nService.LL
	}

	async setLocale(): Promise<void> {
		await loadLocaleAsync(this.selectedLocale)
		this.i18nService.setLocale(this.selectedLocale)
		localStorage.setItem('lang', this.selectedLocale)
	}
}

<div class="toolbar" role="banner">
	<img
		width="40"
		alt="Angular Logo"
		src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
	/>
</div>

<div class="content" role="main">
	<div>
		{{ LL.SELECTED_LOCALE() }}

		<select [(ngModel)]="selectedLocale" (change)="setLocale()">
			<option disabled>{{ LL.CHOOSE_LOCALE() }}</option>
			<option *ngFor="let locale of locales" [ngValue]="locale">{{ locale }}</option>
		</select>
	</div>

	<div>
		<h2>{{ LL.HI({ name: title }) }}</h2>
	</div>

	<div>
		<p>{{ LL.YOUR_NAME() }}</p>
		<input type="text" [(ngModel)]="title" />
	</div>

	<div>
		{{ LL.TODAY({ date: now }) }}
	</div>

	<div>
		<label>
			{{ LL.APPLES_LABEL() }}:
			<input type="number" [(ngModel)]="nrOfApples" min="{0}" />
		</label>

		<label>
			{{ LL.BANANAS_LABEL() }}:
			<input type="number" [(ngModel)]="nrOfBananas" min="{0}" />
		</label>
	</div>

	<div>
		<p>{{ LL.FRUITS({ nrOfApples, nrOfBananas }) }}</p>
	</div>
</div>
